Repository Basalt-Revalidatie/stair-dashboard, pull requests merged in 2023-10, with the labels that each got.

#27 Add sensor calibration and status overview to dashboard
  app/blueprints/backend/templates/admin/dashboard.html
  app/static/css/output.css
Labels: enhancement

#28 Update packages and improve code based on linters
  app/blueprints/backend/__init__.py
  app/const.py
  app/exceptions.py
  app/led_controller.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#29 Add sensor logging to Dashboard
  README.md
  app/blueprints/backend/templates/admin/dashboard.html
  app/blueprints/backend/templates/admin/sensors/show.html
  app/static/js/sockets/logging.js
  app/static/js/sockets/logging/dashboard_log.js
  app/static/js/sockets/logging/main.js
  app/static/js/sockets/logging/sensor_log.js
Labels: enhancement

#30 Refactor to use Application Factories from Flask
  .gitignore
  app/.env.example
  app/__init__.py
  app/blueprints/auth/models.py
  app/led_controller.py
  config.py
  poetry.lock
  pyproject.toml
  run.py
  tests/__init__.py
  tests/conftest.py
  tests/functional/__init__.py
  tests/functional/test_cli.py
  tests/functional/test_frontend.py
  tests/functional/test_users.py
  tests/unit/test_models.py
  tests/unit/test_mqtt.py
Labels: refactor

#31 Run the flask application in Docker
  .dockerignore
  Dockerfile
  app/__init__.py
  app/exceptions.py
  app/mqtt_controller.py
  app/static/js/sockets/init.js
  app/static/package.json
  config.py
  docker-compose.yml
  poetry.lock
  pyproject.toml
  tests/unit/test_mqtt.py
Labels: new-feature

#33 Add Renovate
  .github/renovate.json
Labels: maintenance

#51 I give a shot
  .github/workflows/tests.yaml
  app/__init__.py
  app/led_controller.py
  tests/conftest.py
Labels: bugfix

#58 Improve the pytest code
  tests/conftest.py
  tests/functional/test_auth.py
  tests/functional/test_dashboard.py
  tests/functional/test_frontend.py
  tests/functional/test_users.py
  tests/unit/test_models.py
Labels: enhancement

#61 Redesign of the workout control page
  app/blueprints/frontend/templates/frontend/workouts/control.html
  app/static/css/output.css
  app/static/js/workout.js
  config.py
Labels: enhancement

#62 Add info modals to workout control view
  app/blueprints/frontend/templates/frontend/includes/info_modals.html
  app/blueprints/frontend/templates/frontend/workouts/control.html
  app/static/css/output.css
Labels: enhancement

#63 Add steps counter logic to function
  app/__init__.py
  app/blueprints/frontend/templates/frontend/workouts/control.html
  app/static/js/workout.js
Labels: enhancement

#66 Change sensor names to understandable language
  app/blueprints/frontend/templates/frontend/workouts/control.html
  app/static/css/output.css
Labels: enhancement

#70 Add color dropdown, replacing the picker
  app/blueprints/frontend/templates/frontend/includes/color_dropdown.html
  app/blueprints/frontend/templates/frontend/workouts/control.html
  app/static/css/output.css
  app/static/js/workout.js
Labels: enhancement

#71 Change to gunicorn to run in production
  .dockerignore
  Dockerfile
  app/__init__.py
  app/blueprints/frontend/templates/frontend/workouts/control.html
  app/static/css/output.css
  app/templates/layout_auth.html
  app/templates/layout_backend.html
  app/templates/layout_frontend.html
  docker-compose.yml
  nginx/nginx.conf
  poetry.lock
  pyproject.toml
Labels: enhancement

#72 Start using Ruff formatter
  .github/workflows/linting.yaml
  .pre-commit-config.yaml
  app/__init__.py
  poetry.lock
  pyproject.toml
  tests/functional/test_auth.py
  tests/unit/test_ledstrip.py
Labels: ci

#75 Replace legacy queries for new ones
  app/__init__.py
  app/blueprints/backend/__init__.py
  app/blueprints/frontend/__init__.py
Labels: enhancement

#78 Add validation if sensor exists in database
  app/__init__.py
Labels: bugfix

#81 Add trigger distance to sensor model
  .github/workflows/linting.yaml
  README.md
  app/__init__.py
  app/blueprints/backend/__init__.py
  app/blueprints/backend/models.py
  app/blueprints/backend/templates/admin/sensors/show.html
  tests/unit/test_models.py
Labels: documentation, new-feature

#82 Fix issues from ruff or pylint
  app/__init__.py
  app/blueprints/auth/__init__.py
  app/blueprints/backend/__init__.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/functional/test_auth.py
  tests/functional/test_cli.py
  tests/ruff.toml
  tests/unit/test_models.py
  tests/unit/test_mqtt.py
Labels: enhancement

#84 Update the sensor details with websockets
  app/blueprints/backend/templates/admin/sensors/show.html
  app/static/js/sockets/logging/sensor_log.js
Labels: enhancement

#85 Refactor system control
  app/__init__.py
Labels: refactor

#86 Small refactor on functions names
  app/__init__.py
  app/const.py
  app/led_controller.py
Labels: refactor

#88 Add waterripple animation workout
  app/__init__.py
  app/blueprints/frontend/templates/frontend/includes/workout_cards.html
  app/const.py
  app/led_controller.py
  tests/unit/test_ledstrip.py
Labels: new-feature
